# Usage:
# mk src
# Or manually
# clang -o lib/libtdk.so -fPIC -std=c23 --shared -lyaml src/tdk.c src/tdk_ld.c src/tdk_as.c src/tdk_cc.c src/tdk_mk.c
# clang -std=c23 -o bin/ld -I../libtuim/include -L ../libtuim/lib -ltuim src/ld.c
# clang -std=c23 -o bin/as -I../libtuim/include -L ../libtuim/lib -ltuim src/as.c
# clang -std=c23 -o bin/cc -I../libtuim/include -L ../libtuim/lib -ltuim src/cc.c
# clang -std=c23 -o bin/mk -L lib -ltdk src/mk.c
---
name: tdk
object_type: shared
dependencies:
  - libc.so
  - libcrt.so
  - libyaml.so
  - libposix.so
sources:
  - language: C
    files:
      - tdk.c
      - tdk_ld.c
      - tdk_as.c
      - tdk_cc.c
      - tdk_mk.c
---
name: ld
object_type: executable
dependencies:
  - libc.so
  - libcrt.so
  - libtdk.so
sources:
  - language: C
    files:
      - ld.c
---
name: as
object_type: executable
dependencies:
  - libc.so
  - libcrt.so
  - libtdk.so
sources:
  - language: C
    files:
      - as.c
---
name: cc
object_type: executable
dependencies:
  - libc.so
  - libcrt.so
  - libtdk.so
sources:
  - language: C
    files:
      - cc.c
---
name: mk
object_type: executable
dependencies:
  - libc.so
  - libcrt.so
  - libtdk.so
sources:
  - language: C
    files:
      - mk.c
