#ifndef UNISTD_H
#define UNISTD_H

#if defined(__ARM_ARCH) && (__ARM_ARCH <= 7)
// AARCH32
// arch/arm/tools/syscall.tbl
   #define __NR_restart_syscall	0
   #define __NR_exit	1
   #define __NR_fork	2
   #define __NR_read	3
   #define __NR_write	4
   #define __NR_open	5
   #define __NR_close	6
   #define __NR_creat	8
   #define __NR_link	9
   #define __NR_unlink	10
   #define __NR_execve	11
   #define __NR_chdir	12
   #define __NR_mknod	14
   #define __NR_chmod	15
   #define __NR_lchown	16
   #define __NR_lseek	19
   #define __NR_getpid	20
   #define __NR_mount	21
   #define __NR_setuid	23
   #define __NR_getuid	24
   #define __NR_ptrace	26
   #define __NR_pause	29
   #define __NR_access	33
   #define __NR_nice	34
   #define __NR_sync	36
   #define __NR_kill	37
   #define __NR_rename	38
   #define __NR_mkdir	39
   #define __NR_rmdir	40
   #define __NR_dup	41
   #define __NR_pipe	42
   #define __NR_times	43
   #define __NR_brk	45
   #define __NR_setgid	46
   #define __NR_getgid	47
   #define __NR_geteuid	49
   #define __NR_getegid	50
   #define __NR_acct	51
   #define __NR_umount2	52
   #define __NR_ioctl	54
   #define __NR_fcntl	55
   #define __NR_setpgid	57
   #define __NR_umask	60
   #define __NR_chroot	61
   #define __NR_ustat	62
   #define __NR_dup2	63
   #define __NR_getppid	64
   #define __NR_getpgrp	65
   #define __NR_setsid	66
   #define __NR_sigaction	67
   #define __NR_setreuid	70
   #define __NR_setregid	71
   #define __NR_sigsuspend	72
   #define __NR_sigpending	73
   #define __NR_sethostname	74
   #define __NR_setrlimit	75
   #define __NR_getrusage	77
   #define __NR_gettimeofday_time32	78
   #define __NR_settimeofday_time32	79
   #define __NR_getgroups	80
   #define __NR_setgroups	81
   #define __NR_symlink	83
   #define __NR_readlink	85
   #define __NR_uselib	86
   #define __NR_swapon	87
   #define __NR_reboot	88
   #define __NR_munmap	91
   #define __NR_truncate	92
   #define __NR_ftruncate	93
   #define __NR_fchmod	94
   #define __NR_fchown	95
   #define __NR_getpriority	96
   #define __NR_setpriority	97
   #define __NR_statfs	99
   #define __NR_fstatfs	100
   #define __NR_syslog	103
   #define __NR_setitimer	104
   #define __NR_getitimer	105
   #define __NR_stat	106
   #define __NR_lstat	107
   #define __NR_fstat	108
   #define __NR_vhangup	111
   #define __NR_wait4	114
   #define __NR_swapoff	115
   #define __NR_sysinfo	116
   #define __NR_fsync	118
   #define __NR_sigreturn	119
   #define __NR_clone	120
   #define __NR_setdomainname	121
   #define __NR_uname	122
   #define __NR_adjtimex	124
   #define __NR_mprotect	125
   #define __NR_sigprocmask	126
   #define __NR_init_module	128
   #define __NR_delete_module	129
   #define __NR_quotactl	131
   #define __NR_getpgid	132
   #define __NR_fchdir	133
   #define __NR_bdflush	134
   #define __NR_sysfs	135
   #define __NR_personality	136
   #define __NR_setfsuid	138
   #define __NR_setfsgid	139
   #define __NR__llseek	140
   #define __NR_getdents	141
   #define __NR__newselect	142
   #define __NR_flock	143
   #define __NR_msync	144
   #define __NR_readv	145
   #define __NR_writev	146
   #define __NR_getsid	147
   #define __NR_fdatasync	148
   #define __NR__sysctl	149
   #define __NR_mlock	150
   #define __NR_munlock	151
   #define __NR_mlockall	152
   #define __NR_munlockall	153
   #define __NR_sched_setparam	154
   #define __NR_sched_getparam	155
   #define __NR_sched_setscheduler	156
   #define __NR_sched_getscheduler	157
   #define __NR_sched_yield	158
   #define __NR_sched_get_priority_max	159
   #define __NR_sched_get_priority_min	160
   #define __NR_sched_rr_get_interval	161
   #define __NR_nanosleep	162
   #define __NR_mremap	163
   #define __NR_setresuid	164
   #define __NR_getresuid	165
   #define __NR_poll	168
   #define __NR_nfsservctl	169
   #define __NR_setresgid	170
   #define __NR_getresgid	171
   #define __NR_prctl	172
   #define __NR_rt_sigreturn	173
   #define __NR_rt_sigaction	174
   #define __NR_rt_sigprocmask	175
   #define __NR_rt_sigpending	176
   #define __NR_rt_sigtimedwait	177
   #define __NR_rt_sigqueueinfo	178
   #define __NR_rt_sigsuspend	179
   #define __NR_pread64	180
   #define __NR_pwrite64	181
   #define __NR_chown	182
   #define __NR_getcwd	183
   #define __NR_capget	184
   #define __NR_capset	185
   #define __NR_sigaltstack	186
   #define __NR_sendfile	187
   #define __NR_vfork	190
   #define __NR_ugetrlimit	191
   #define __NR_mmap	192
   #define __NR_mmap2	192
   #define __NR_truncate64	193
   #define __NR_ftruncate64	194
   #define __NR_stat64	195
   #define __NR_lstat64	196
   #define __NR_fstat64	197
   #define __NR_lchown32	198
   #define __NR_getuid32	199
   #define __NR_getgid32	200
   #define __NR_geteuid32	201
   #define __NR_getegid32	202
   #define __NR_setreuid32	203
   #define __NR_setregid32	204
   #define __NR_getgroups32	205
   #define __NR_setgroups32	206
   #define __NR_fchown32	207
   #define __NR_setresuid32	208
   #define __NR_getresuid32	209
   #define __NR_setresgid32	210
   #define __NR_getresgid32	211
   #define __NR_chown32	212
   #define __NR_setuid32	213
   #define __NR_setgid32	214
   #define __NR_setfsuid32	215
   #define __NR_setfsgid32	216
   #define __NR_getdents64	217
   #define __NR_pivot_root	218
   #define __NR_mincore	219
   #define __NR_madvise	220
   #define __NR_fcntl64	221
   #define __NR_gettid	224
   #define __NR_readahead	225
   #define __NR_setxattr	226
   #define __NR_lsetxattr	227
   #define __NR_fsetxattr	228
   #define __NR_getxattr	229
   #define __NR_lgetxattr	230
   #define __NR_fgetxattr	231
   #define __NR_listxattr	232
   #define __NR_llistxattr	233
   #define __NR_flistxattr	234
   #define __NR_removexattr	235
   #define __NR_lremovexattr	236
   #define __NR_fremovexattr	237
   #define __NR_tkill	238
   #define __NR_sendfile64	239
   #define __NR_futex	240
   #define __NR_sched_setaffinity	241
   #define __NR_sched_getaffinity	242
   #define __NR_io_setup	243
   #define __NR_io_destroy	244
   #define __NR_io_getevents	245
   #define __NR_io_submit	246
   #define __NR_io_cancel	247
   #define __NR_exit_group	248
   #define __NR_lookup_dcookie	249
   #define __NR_epoll_create	250
   #define __NR_epoll_ctl	251
   #define __NR_epoll_wait	252
   #define __NR_remap_file_pages	253
   #define __NR_set_tid_address	256
   #define __NR_timer_create	257
   #define __NR_timer_settime32	258
   #define __NR_timer_gettime32	259
   #define __NR_timer_getoverrun	260
   #define __NR_timer_delete	261
   #define __NR_clock_settime32	262
   #define __NR_clock_gettime32	263
   #define __NR_clock_getres_time32	264
   #define __NR_clock_nanosleep_time32	265
   #define __NR_statfs64	266
   #define __NR_fstatfs64	267
   #define __NR_tgkill	268
   #define __NR_utimes	269
   #define __NR_fadvise64_64	270
   #define __NR_arm_fadvise64_64	270
   #define __NR_pciconfig_iobase	271
   #define __NR_pciconfig_read	272
   #define __NR_pciconfig_write	273
   #define __NR_mq_open	274
   #define __NR_mq_unlink	275
   #define __NR_mq_timedsend	276
   #define __NR_mq_timedreceive	277
   #define __NR_mq_notify	278
   #define __NR_mq_getsetattr	279
   #define __NR_waitid	280
   #define __NR_socket	281
   #define __NR_bind	282
   #define __NR_connect	283
   #define __NR_listen	284
   #define __NR_accept	285
   #define __NR_getsockname	286
   #define __NR_getpeername	287
   #define __NR_socketpair	288
   #define __NR_send	289
   #define __NR_sendto	290
   #define __NR_recv	291
   #define __NR_recvfrom	292
   #define __NR_shutdown	293
   #define __NR_setsockopt	294
   #define __NR_getsockopt	295
   #define __NR_sendmsg	296
   #define __NR_recvmsg	297
   #define __NR_semop	298
   #define __NR_semget	299
   #define __NR_semctl	300
   #define __NR_msgsnd	301
   #define __NR_msgrcv	302
   #define __NR_msgget	303
   #define __NR_msgctl	304
   #define __NR_shmat	305
   #define __NR_shmdt	306
   #define __NR_shmget	307
   #define __NR_shmctl	308
   #define __NR_add_key	309
   #define __NR_request_key	310
   #define __NR_keyctl	311
   #define __NR_semtimedop	312
   #define __NR_vserver	313
   #define __NR_ioprio_set	314
   #define __NR_ioprio_get	315
   #define __NR_inotify_init	316
   #define __NR_inotify_add_watch	317
   #define __NR_inotify_rm_watch	318
   #define __NR_mbind	319
   #define __NR_get_mempolicy	320
   #define __NR_set_mempolicy	321
   #define __NR_openat	322
   #define __NR_mkdirat	323
   #define __NR_mknodat	324
   #define __NR_fchownat	325
   #define __NR_futimesat	326
   #define __NR_fstatat64	327
   #define __NR_unlinkat	328
   #define __NR_renameat	329
   #define __NR_linkat	330
   #define __NR_symlinkat	331
   #define __NR_readlinkat	332
   #define __NR_fchmodat	333
   #define __NR_faccessat	334
   #define __NR_pselect6	335
   #define __NR_ppoll	336
   #define __NR_unshare	337
   #define __NR_set_robust_list	338
   #define __NR_get_robust_list	339
   #define __NR_splice	340
   #define __NR_sync_file_range2	341
   #define __NR_arm_sync_file_range	341
   #define __NR_tee	342
   #define __NR_vmsplice	343
   #define __NR_move_pages	344
   #define __NR_getcpu	345
   #define __NR_epoll_pwait	346
   #define __NR_kexec_load	347
   #define __NR_utimensat	348
   #define __NR_signalfd	349
   #define __NR_timerfd_create	350
   #define __NR_eventfd	351
   #define __NR_fallocate	352
   #define __NR_timerfd_settime32	353
   #define __NR_timerfd_gettime32	354
   #define __NR_signalfd4	355
   #define __NR_eventfd2	356
   #define __NR_epoll_create1	357
   #define __NR_dup3	358
   #define __NR_pipe2	359
   #define __NR_inotify_init1	360
   #define __NR_preadv	361
   #define __NR_pwritev	362
   #define __NR_rt_tgsigqueueinfo	363
   #define __NR_perf_event_open	364
   #define __NR_recvmmsg	365
   #define __NR_accept4	366
   #define __NR_fanotify_init	367
   #define __NR_fanotify_mark	368
   #define __NR_prlimit64	369
   #define __NR_name_to_handle_at	370
   #define __NR_open_by_handle_at	371
   #define __NR_clock_adjtime	372
   #define __NR_syncfs	373
   #define __NR_sendmmsg	374
   #define __NR_setns	375
   #define __NR_process_vm_readv	376
   #define __NR_process_vm_writev	377
   #define __NR_kcmp		378
   #define __NR_finit_module	379
   #define __NR_sched_setattr	380
   #define __NR_sched_getattr	381
   #define __NR_renameat2	382
   #define __NR_seccomp	383
   #define __NR_getrandom	384
   #define __NR_memfd_create	385
   #define __NR_bpf	386
   #define __NR_execveat	387
   #define __NR_userfaultfd	388
   #define __NR_membarrier		389
   #define __NR_mlock2		390
   #define __NR_copy_file_range	391
   #define __NR_preadv2	392
   #define __NR_pwritev2	393
   #define __NR_pkey_mprotect	394
   #define __NR_pkey_alloc	395
   #define __NR_pkey_free	396
   #define __NR_statx	397
   #define __NR_rseq	398
   #define __NR_io_pgetevents	399
   #define __NR_migrate_pages	400
   #define __NR_kexec_file_load	401
   #define __NR_clock_gettime64	403
   #define __NR_clock_settime64	404
   #define __NR_clock_adjtime64	405
   #define __NR_clock_getres_time64	406
   #define __NR_clock_nanosleep_time64	407
   #define __NR_timer_gettime64	408
   #define __NR_timer_settime64	409
   #define __NR_timerfd_gettime64	410
   #define __NR_timerfd_settime64	411
   #define __NR_utimensat_time64	412
   #define __NR_pselect6_time64	413
   #define __NR_ppoll_time64	414
   #define __NR_io_pgetevents_time64	416
   #define __NR_recvmmsg_time64	417
   #define __NR_mq_timedsend_time64	418
   #define __NR_mq_timedreceive_time64	419
   #define __NR_semtimedop_time64	420
   #define __NR_rt_sigtimedwait_time64	421
   #define __NR_futex_time64	422
   #define __NR_sched_rr_get_interval_time64	423
   #define __NR_pidfd_send_signal	424
   #define __NR_io_uring_setup	425
   #define __NR_io_uring_enter	426
   #define __NR_io_uring_register	427
   #define __NR_open_tree		428
   #define __NR_move_mount		429
   #define __NR_fsopen		430
   #define __NR_fsconfig		431
   #define __NR_fsmount		432
   #define __NR_fspick		433
   #define __NR_pidfd_open		434
   #define __NR_clone3		435
   #define __NR_close_range	436
   #define __NR_openat2		437
   #define __NR_pidfd_getfd	438
   #define __NR_faccessat2		439
   #define __NR_process_madvise	440
   #define __NR_epoll_pwait2	441
   #define __NR_mount_setattr	442
   #define __NR_landlock_create_ruleset	444
   #define __NR_landlock_add_rule	445
   #define __NR_landlock_restrict_self	446
   #define __NR_process_mrelease	448
   #define __NR_futex_waitv	449
   #define __NR_set_mempolicy_home_node	450
   #define __NR_cachestat		451
   #define __NR_fchmodat2		452
#elif defined(__ARM_ARCH) && (__ARM_ARCH >= 8)
// AARCH64
   #define __NR_io_setup 0
   #define __NR_io_destroy 1
   #define __NR_io_submit 2
   #define __NR_io_cancel 3
   #define __NR_io_getevents 4
   #define __NR_setxattr 5
   #define __NR_lsetxattr 6
   #define __NR_fsetxattr 7
   #define __NR_getxattr 8
   #define __NR_lgetxattr 9
   #define __NR_fgetxattr 10
   #define __NR_listxattr 11
   #define __NR_llistxattr 12
   #define __NR_flistxattr 13
   #define __NR_removexattr 14
   #define __NR_lremovexattr 15
   #define __NR_fremovexattr 16
   #define __NR_getcwd 17
   #define __NR_lookup_dcookie 18
   #define __NR_eventfd2 19
   #define __NR_epoll_create1 20
   #define __NR_epoll_ctl 21
   #define __NR_epoll_pwait 22
   #define __NR_dup 23
   #define __NR_dup3 24
   #define __NR_fcntl 25
   #define __NR_inotify_init1 26
   #define __NR_inotify_add_watch 27
   #define __NR_inotify_rm_watch 28
   #define __NR_ioctl 29
   #define __NR_ioprio_set 30
   #define __NR_ioprio_get 31
   #define __NR_flock 32
   #define __NR_mknodat 33
   #define __NR_mkdirat 34
   #define __NR_unlinkat 35
   #define __NR_symlinkat 36
   #define __NR_linkat 37
   #define __NR_renameat 38
   #define __NR_umount2 39
   #define __NR_mount 40
   #define __NR_pivot_root 41
   #define __NR_nfsservctl 42
   #define __NR_statfs 43
   #define __NR_fstatfs 44
   #define __NR_truncate 45
   #define __NR_ftruncate 46
   #define __NR_fallocate 47
   #define __NR_faccessat 48
   #define __NR_chdir 49
   #define __NR_fchdir 50
   #define __NR_chroot 51
   #define __NR_fchmod 52
   #define __NR_fchmodat 53
   #define __NR_fchownat 54
   #define __NR_fchown 55
   #define __NR_openat 56
   #define __NR_close 57
   #define __NR_vhangup 58
   #define __NR_pipe2 59
   #define __NR_quotactl 60
   #define __NR_getdents64 61
   #define __NR_lseek 62
   #define __NR_read 63
   #define __NR_write 64
   #define __NR_readv 65
   #define __NR_writev 66
   #define __NR_pread64 67
   #define __NR_pwrite64 68
   #define __NR_preadv 69
   #define __NR_pwritev 70
   #define __NR_sendfile 71
   #define __NR_pselect6 72
   #define __NR_ppoll 73
   #define __NR_signalfd4 74
   #define __NR_vmsplice 75
   #define __NR_splice 76
   #define __NR_tee 77
   #define __NR_readlinkat 78
   #define __NR_newfstatat 79
   #define __NR_fstat 80
   #define __NR_sync 81
   #define __NR_fsync 82
   #define __NR_fdatasync 83
   #define __NR_sync_file_range 84
   #define __NR_timerfd_create 85
   #define __NR_timerfd_settime 86
   #define __NR_timerfd_gettime 87
   #define __NR_utimensat 88
   #define __NR_acct 89
   #define __NR_capget 90
   #define __NR_capset 91
   #define __NR_personality 92
   #define __NR_exit 93
   #define __NR_exit_group 94
   #define __NR_waitid 95
   #define __NR_set_tid_address 96
   #define __NR_unshare 97
   #define __NR_futex 98
   #define __NR_set_robust_list 99
   #define __NR_get_robust_list 100
   #define __NR_nanosleep 101
   #define __NR_getitimer 102
   #define __NR_setitimer 103
   #define __NR_kexec_load 104
   #define __NR_init_module 105
   #define __NR_delete_module 106
   #define __NR_timer_create 107
   #define __NR_timer_gettime 108
   #define __NR_timer_getoverrun 109
   #define __NR_timer_settime 110
   #define __NR_timer_delete 111
   #define __NR_clock_settime 112
   #define __NR_clock_gettime 113
   #define __NR_clock_getres 114
   #define __NR_clock_nanosleep 115
   #define __NR_syslog 116
   #define __NR_ptrace 117
   #define __NR_sched_setparam 118
   #define __NR_sched_setscheduler 119
   #define __NR_sched_getscheduler 120
   #define __NR_sched_getparam 121
   #define __NR_sched_setaffinity 122
   #define __NR_sched_getaffinity 123
   #define __NR_sched_yield 124
   #define __NR_sched_get_priority_max 125
   #define __NR_sched_get_priority_min 126
   #define __NR_sched_rr_get_interval 127
   #define __NR_restart_syscall 128
   #define __NR_kill 129
   #define __NR_tkill 130
   #define __NR_tgkill 131
   #define __NR_sigaltstack 132
   #define __NR_rt_sigsuspend 133
   #define __NR_rt_sigaction 134
   #define __NR_rt_sigprocmask 135
   #define __NR_rt_sigpending 136
   #define __NR_rt_sigtimedwait 137
   #define __NR_rt_sigqueueinfo 138
   #define __NR_rt_sigreturn 139
   #define __NR_setpriority 140
   #define __NR_getpriority 141
   #define __NR_reboot 142
   #define __NR_setregid 143
   #define __NR_setgid 144
   #define __NR_setreuid 145
   #define __NR_setuid 146
   #define __NR_setresuid 147
   #define __NR_getresuid 148
   #define __NR_setresgid 149
   #define __NR_getresgid 150
   #define __NR_setfsuid 151
   #define __NR_setfsgid 152
   #define __NR_times 153
   #define __NR_setpgid 154
   #define __NR_getpgid 155
   #define __NR_getsid 156
   #define __NR_setsid 157
   #define __NR_getgroups 158
   #define __NR_setgroups 159
   #define __NR_uname 160
   #define __NR_sethostname 161
   #define __NR_setdomainname 162
   #define __NR_getrlimit 163
   #define __NR_setrlimit 164
   #define __NR_getrusage 165
   #define __NR_umask 166
   #define __NR_prctl 167
   #define __NR_getcpu 168
   #define __NR_gettimeofday 169
   #define __NR_settimeofday 170
   #define __NR_adjtimex 171
   #define __NR_getpid 172
   #define __NR_getppid 173
   #define __NR_getuid 174
   #define __NR_geteuid 175
   #define __NR_getgid 176
   #define __NR_getegid 177
   #define __NR_gettid 178
   #define __NR_sysinfo 179
   #define __NR_mq_open 180
   #define __NR_mq_unlink 181
   #define __NR_mq_timedsend 182
   #define __NR_mq_timedreceive 183
   #define __NR_mq_notify 184
   #define __NR_mq_getsetattr 185
   #define __NR_msgget 186
   #define __NR_msgctl 187
   #define __NR_msgrcv 188
   #define __NR_msgsnd 189
   #define __NR_semget 190
   #define __NR_semctl 191
   #define __NR_semtimedop 192
   #define __NR_semop 193
   #define __NR_shmget 194
   #define __NR_shmctl 195
   #define __NR_shmat 196
   #define __NR_shmdt 197
   #define __NR_socket 198
   #define __NR_socketpair 199
   #define __NR_bind 200
   #define __NR_listen 201
   #define __NR_accept 202
   #define __NR_connect 203
   #define __NR_getsockname 204
   #define __NR_getpeername 205
   #define __NR_sendto 206
   #define __NR_recvfrom 207
   #define __NR_setsockopt 208
   #define __NR_getsockopt 209
   #define __NR_shutdown 210
   #define __NR_sendmsg 211
   #define __NR_recvmsg 212
   #define __NR_readahead 213
   #define __NR_brk 214
   #define __NR_munmap 215
   #define __NR_mremap 216
   #define __NR_add_key 217
   #define __NR_request_key 218
   #define __NR_keyctl 219
   #define __NR_clone 220
   #define __NR_execve 221
   #define __NR_mmap 222
   #define __NR_fadvise64 223
   #define __NR_swapon 224
   #define __NR_swapoff 225
   #define __NR_mprotect 226
   #define __NR_msync 227
   #define __NR_mlock 228
   #define __NR_munlock 229
   #define __NR_mlockall 230
   #define __NR_munlockall 231
   #define __NR_mincore 232
   #define __NR_madvise 233
   #define __NR_remap_file_pages 234
   #define __NR_mbind 235
   #define __NR_get_mempolicy 236
   #define __NR_set_mempolicy 237
   #define __NR_migrate_pages 238
   #define __NR_move_pages 239
   #define __NR_rt_tgsigqueueinfo 240
   #define __NR_perf_event_open 241
   #define __NR_accept4 242
   #define __NR_recvmmsg 243
   #define __NR_wait4 260
   #define __NR_prlimit64 261
   #define __NR_fanotify_init 262
   #define __NR_fanotify_mark 263
   #define __NR_name_to_handle_at 264
   #define __NR_open_by_handle_at 265
   #define __NR_clock_adjtime 266
   #define __NR_syncfs 267
   #define __NR_setns 268
   #define __NR_sendmmsg 269
   #define __NR_process_vm_readv 270
   #define __NR_process_vm_writev 271
   #define __NR_kcmp 272
   #define __NR_finit_module 273
   #define __NR_sched_setattr 274
   #define __NR_sched_getattr 275
   #define __NR_renameat2 276
   #define __NR_seccomp 277
   #define __NR_getrandom 278
   #define __NR_memfd_create 279
   #define __NR_bpf 280
   #define __NR_execveat 281
   #define __NR_userfaultfd 282
   #define __NR_membarrier 283
   #define __NR_mlock2 284
   #define __NR_copy_file_range 285
   #define __NR_preadv2 286
   #define __NR_pwritev2 287
   #define __NR_pkey_mprotect 288
   #define __NR_pkey_alloc 289
   #define __NR_pkey_free 290
   #define __NR_statx 291
   #define __NR_io_pgetevents 292
   #define __NR_rseq 293
   #define __NR_kexec_file_load 294
   #define __NR_pidfd_send_signal 424
   #define __NR_io_uring_setup 425
   #define __NR_io_uring_enter 426
   #define __NR_io_uring_register 427
   #define __NR_open_tree		428
   #define __NR_move_mount		429
   #define __NR_fsopen		430
   #define __NR_fsconfig		431
   #define __NR_fsmount		432
   #define __NR_fspick		433
   #define __NR_pidfd_open		434
   #define __NR_clone3		435
   #define __NR_close_range	436
   #define __NR_openat2		437
   #define __NR_pidfd_getfd	438
   #define __NR_faccessat2		439
   #define __NR_process_madvise	440
   #define __NR_epoll_pwait2	441
   #define __NR_mount_setattr	442
   #define __NR_landlock_create_ruleset	444
   #define __NR_landlock_add_rule	445
   #define __NR_landlock_restrict_self	446
   #define __NR_process_mrelease	448
   #define __NR_futex_waitv	449
   #define __NR_set_mempolicy_home_node	450
   #define __NR_cachestat		451
   #define __NR_fchmodat2		452
#elif defined(__i386__)
// i386
// arch/x86/entry/syscalls/syscall_32.tbl
   #define __NR_read    3
   #define __NR_write   4
   #define __NR_open    5
   #define __NR_close   6
   #define __NR_stat    106
   #define __NR_fstat   108
   #define __NR_lseek   19
   #define __NR_mkdir   39
   #define __NR_rmdir   40
   #define __NR_fork    2

   #define __NR_write      4
   #define __NR_mmap       90
   #define __NR_munmap     91
   #define __NR_open       5
   #define __NR_close      6
   #define __NR_mprotect   125
#elif defined(__x86_64__)
// AMD64
// arch/x86/entry/syscalls/syscall_64.tbl
   #define __NR_read				0
   #define __NR_write				1
   #define __NR_open				2
   #define __NR_close				3
   #define __NR_stat				4
   #define __NR_fstat				5
   #define __NR_lstat				6
   #define __NR_poll				7
   #define __NR_lseek				8
   #define __NR_mmap				9
   #define __NR_mprotect			10
   #define __NR_munmap				11
   #define __NR_brk				12
   #define __NR_rt_sigaction		13
   #define __NR_rt_sigprocmask		14
   #define __NR_rt_sigreturn		15
   #define __NR_ioctl				16
   #define __NR_pread64			17
   #define __NR_pwrite64			18
   #define __NR_readv				19
   #define __NR_writev				20
   #define __NR_access				21
   #define __NR_pipe				22
   #define __NR_select				23
   #define __NR_sched_yield		24
   #define __NR_mremap				25
   #define __NR_msync				26
   #define __NR_mincore			27
   #define __NR_madvise			28
   #define __NR_shmget				29
   #define __NR_shmat				30
   #define __NR_shmctl				31
   #define __NR_dup				32
   #define __NR_dup2				33
   #define __NR_pause				34
   #define __NR_nanosleep			35
   #define __NR_getitimer			36
   #define __NR_alarm				37
   #define __NR_setitimer			38
   #define __NR_getpid				39
   #define __NR_sendfile			40
   #define __NR_socket				41
   #define __NR_connect			42
   #define __NR_accept				43
   #define __NR_sendto				44
   #define __NR_recvfrom			45
   #define __NR_sendmsg			46
   #define __NR_recvmsg			47
   #define __NR_shutdown			48
   #define __NR_bind				49
   #define __NR_listen				50
   #define __NR_getsockname		51
   #define __NR_getpeername		52
   #define __NR_socketpair			53
   #define __NR_setsockopt			54
   #define __NR_getsockopt			55
   #define __NR_clone				56
   #define __NR_fork				57
   #define __NR_vfork				58
   #define __NR_execve				59
   #define __NR_exit				60
   #define __NR_wait4				61
   #define __NR_kill				62
   #define __NR_uname				63
   #define __NR_semget				64
   #define __NR_semop				65
   #define __NR_semctl				66
   #define __NR_shmdt				67
   #define __NR_msgget				68
   #define __NR_msgsnd				69
   #define __NR_msgrcv				70
   #define __NR_msgctl				71
   #define __NR_fcntl				72
   #define __NR_flock				73
   #define __NR_fsync				74
   #define __NR_fdatasync			75
   #define __NR_truncate			76
   #define __NR_ftruncate			77
   #define __NR_getdents			78
   #define __NR_getcwd				79
   #define __NR_chdir				80
   #define __NR_fchdir				81
   #define __NR_rename				82
   #define __NR_mkdir				83
   #define __NR_rmdir				84
   #define __NR_creat				85
   #define __NR_link				86
   #define __NR_unlink				87
   #define __NR_symlink			88
   #define __NR_readlink			89
   #define __NR_chmod				90
   #define __NR_fchmod				91
   #define __NR_chown				92
   #define __NR_fchown				93
   #define __NR_lchown				94
   #define __NR_umask				95
   #define __NR_gettimeofday		96
   #define __NR_getrlimit			97
   #define __NR_getrusage			98
   #define __NR_sysinfo			99
   #define __NR_times				100
   #define __NR_ptrace				101
   #define __NR_getuid				102
   #define __NR_syslog				103
   #define __NR_getgid				104
   #define __NR_setuid				105
   #define __NR_setgid				106
   #define __NR_geteuid			107
   #define __NR_getegid			108
   #define __NR_setpgid			109
   #define __NR_getppid			110
   #define __NR_getpgrp			111
   #define __NR_setsid				112
   #define __NR_setreuid			113
   #define __NR_setregid			114
   #define __NR_getgroups			115
   #define __NR_setgroups			116
   #define __NR_setresuid			117
   #define __NR_getresuid			118
   #define __NR_setresgid			119
   #define __NR_getresgid			120
   #define __NR_getpgid			121
   #define __NR_setfsuid			122
   #define __NR_setfsgid			123
   #define __NR_getsid				124
   #define __NR_capget				125
   #define __NR_capset				126
   #define __NR_rt_sigpending		127
   #define __NR_rt_sigtimedwait	128
   #define __NR_rt_sigqueueinfo	129
   #define __NR_rt_sigsuspend		130
   #define __NR_sigaltstack		131
   #define __NR_utime				132
   #define __NR_mknod				133
   #define __NR_uselib				134
   #define __NR_personality		135
   #define __NR_ustat				136
   #define __NR_statfs				137
   #define __NR_fstatfs			138
   #define __NR_sysfs				139
   #define __NR_getpriority			140
   #define __NR_setpriority			141
   #define __NR_sched_setparam			142
   #define __NR_sched_getparam			143
   #define __NR_sched_setscheduler		144
   #define __NR_sched_getscheduler		145
   #define __NR_sched_get_priority_max	146
   #define __NR_sched_get_priority_min	147
   #define __NR_sched_rr_get_interval	148
   #define __NR_mlock					149
   #define __NR_munlock				150
   #define __NR_mlockall				151
   #define __NR_munlockall				152
   #define __NR_vhangup				153
   #define __NR_modify_ldt				154
   #define __NR_pivot_root				155
   #define __NR__sysctl				156
   #define __NR_prctl					157
   #define __NR_arch_prctl				158
   #define __NR_adjtimex				159
   #define __NR_setrlimit				160
   #define __NR_chroot					161
   #define __NR_sync					162
   #define __NR_acct					163
   #define __NR_settimeofday			164
   #define __NR_mount					165
   #define __NR_umount2				166
   #define __NR_swapon					167
   #define __NR_swapoff				168
   #define __NR_reboot					169
   #define __NR_sethostname			170
   #define __NR_setdomainname			171
   #define __NR_iopl					172
   #define __NR_ioperm					173
   #define __NR_create_module			174
   #define __NR_init_module			175
   #define __NR_delete_module			176
   #define __NR_get_kernel_syms		177
   #define __NR_query_module			178
   #define __NR_quotactl				179
   #define __NR_nfsservctl				180
   #define __NR_getpmsg				181
   #define __NR_putpmsg				182
   #define __NR_afs_syscall			183
   #define __NR_tuxcall				184
   #define __NR_security				185
   #define __NR_gettid					186
   #define __NR_readahead				187
   #define __NR_setxattr				188
   #define __NR_lsetxattr				189
   #define __NR_fsetxattr				190
   #define __NR_getxattr				191
   #define __NR_lgetxattr				192
   #define __NR_fgetxattr				193
   #define __NR_listxattr				194
   #define __NR_llistxattr				195
   #define __NR_flistxattr				196
   #define __NR_removexattr			197
   #define __NR_lremovexattr			198
   #define __NR_fremovexattr			199
   #define __NR_tkill					200
   #define __NR_time					201
   #define __NR_futex					202
   #define __NR_sched_setaffinity		203
   #define __NR_sched_getaffinity		204
   #define __NR_set_thread_area		205
   #define __NR_io_setup				206
   #define __NR_io_destroy				207
   #define __NR_io_getevents			208
   #define __NR_io_submit				209
   #define __NR_io_cancel				210
   #define __NR_get_thread_area		211
   #define __NR_lookup_dcookie			212
   #define __NR_epoll_create			213
   #define __NR_epoll_ctl_old			214
   #define __NR_epoll_wait_old			215
   #define __NR_remap_file_pages		216
   #define __NR_getdents64				217
   #define __NR_set_tid_address		218
   #define __NR_restart_syscall		219
   #define __NR_semtimedop				220
   #define __NR_fadvise64				221
   #define __NR_timer_create			222
   #define __NR_timer_settime			223
   #define __NR_timer_gettime			224
   #define __NR_timer_getoverrun		225
   #define __NR_timer_delete			226
   #define __NR_clock_settime			227
   #define __NR_clock_gettime			228
   #define __NR_clock_getres			229
   #define __NR_clock_nanosleep		230
   #define __NR_exit_group				231
   #define __NR_epoll_wait				232
   #define __NR_epoll_ctl				233
   #define __NR_tgkill					234
   #define __NR_utimes					235
   #define __NR_vserver				236
   #define __NR_mbind					237
   #define __NR_set_mempolicy			238
   #define __NR_get_mempolicy			239
   #define __NR_mq_open				240
   #define __NR_mq_unlink				241
   #define __NR_mq_timedsend			242
   #define __NR_mq_timedreceive		243
   #define __NR_mq_notify				244
   #define __NR_mq_getsetattr			245
   #define __NR_kexec_load				246
   #define __NR_waitid					247
   #define __NR_add_key				248
   #define __NR_request_key			249
   #define __NR_keyctl					250
   #define __NR_ioprio_set				251
   #define __NR_ioprio_get				252
   #define __NR_inotify_init			253
   #define __NR_inotify_add_watch		254
   #define __NR_inotify_rm_watch		255
   #define __NR_migrate_pages			256
   #define __NR_openat					257
   #define __NR_mkdirat				258
   #define __NR_mknodat				259
   #define __NR_fchownat				260
   #define __NR_futimesat				261
   #define __NR_newfstatat				262
   #define __NR_unlinkat				263
   #define __NR_renameat				264
   #define __NR_linkat					265
   #define __NR_symlinkat				266
   #define __NR_readlinkat				267
   #define __NR_fchmodat				268
   #define __NR_faccessat				269
   #define __NR_pselect6				270
   #define __NR_ppoll					271
   #define __NR_unshare				272
   #define __NR_set_robust_list		273
   #define __NR_get_robust_list		274
   #define __NR_splice					275
   #define __NR_tee					276
   #define __NR_sync_file_range		277
   #define __NR_vmsplice				278
   #define __NR_move_pages				279
   #define __NR_utimensat				280
   #define __NR_epoll_pwait			281
   #define __NR_signalfd				282
   #define __NR_timerfd_create			283
   #define __NR_eventfd				284
   #define __NR_fallocate				285
   #define __NR_timerfd_settime		286
   #define __NR_timerfd_gettime		287
   #define __NR_accept4				288
   #define __NR_signalfd4				289
   #define __NR_eventfd2				290
   #define __NR_epoll_create1			291
   #define __NR_dup3					292
   #define __NR_pipe2					293
   #define __NR_inotify_init1			294
   #define __NR_preadv					295
   #define __NR_pwritev				296
   #define __NR_rt_tgsigqueueinfo		297
   #define __NR_perf_event_open		298
   #define __NR_recvmmsg				299
   #define __NR_fanotify_init			300
   #define __NR_fanotify_mark			301
   #define __NR_prlimit64				302
   #define __NR_name_to_handle_at			303
   #define __NR_open_by_handle_at			304
   #define __NR_clock_adjtime			305
   #define __NR_syncfs				306
   #define __NR_sendmmsg				307
   #define __NR_setns				308
   #define __NR_getcpu				309
   #define __NR_process_vm_readv			310
   #define __NR_process_vm_writev			311
   #define __NR_kcmp				312
   #define __NR_finit_module			313
   #define __NR_sched_setattr			314
   #define __NR_sched_getattr			315
   #define __NR_renameat2				316
   #define __NR_seccomp				317
   #define __NR_getrandom				318
   #define __NR_memfd_create			319
   #define __NR_kexec_file_load			320
   #define __NR_bpf				321
   #define __NR_execveat				322
   #define __NR_userfaultfd			323
   #define __NR_membarrier				324
   #define __NR_mlock2				325
   #define __NR_copy_file_range			326
   #define __NR_preadv2				327
   #define __NR_pwritev2				328
   #define __NR_pkey_mprotect			329
   #define __NR_pkey_alloc				330
   #define __NR_pkey_free				331
   #define __NR_statx				332
   #define __NR_io_pgetevents			333
   #define __NR_rseq				334
   #define __NR_pidfd_send_signal			424
   #define __NR_io_uring_setup			425
   #define __NR_io_uring_enter			426
   #define __NR_io_uring_register			427
   #define __NR_open_tree		428
   #define __NR_move_mount		429
   #define __NR_fsopen		430
   #define __NR_fsconfig		431
   #define __NR_fsmount		432
   #define __NR_fspick		433
   #define __NR_pidfd_open		434
   #define __NR_clone3		435
   #define __NR_close_range	436
   #define __NR_openat2		437
   #define __NR_pidfd_getfd	438
   #define __NR_faccessat2		439
   #define __NR_process_madvise	440
   #define __NR_epoll_pwait2	441
   #define __NR_mount_setattr	442
   #define __NR_landlock_create_ruleset	444
   #define __NR_landlock_add_rule	445
   #define __NR_landlock_restrict_self	446
   #define __NR_memfd_secret	447
   #define __NR_process_mrelease	448
   #define __NR_futex_waitv	449
   #define __NR_set_mempolicy_home_node	450
   #define __NR_cachestat		451
   #define __NR_fchmodat2		452
#else
// scripts/syscall.tbl
// include/uapi/asm-generic/unistd.h
// RISC-V
// AARCH64

   #define __NR_read            63
   #define __NR_write           64
   #define __NR_open            56
   #define __NR_close           57
   #define __NR_stat            79   /* __NR3264_fstat */
   #define __NR_fstat           80   /* __NR3264_fstat */
   #define __NR_lseek           62   /* __NR3264_lseek */
   #define __NR_mkdir           83
   #define __NR_rmdir           /* not in generic? use openat + unlinkat */
   #define __NR_fork            1079

   /* Read/write vectors */
   #define __NR_readv           65
   #define __NR_writev          66
   #define __NR_pread64         67
   #define __NR_pwrite64        68

   /* File descriptor operations */
   #define __NR_pipe2           59
   #define __NR_dup2            1041
   #define __NR_fsync           82
   #define __NR_fdatasync       83
   #define __NR_sync            81

   /* File tree / directory */
   #define __NR_getdents64      61
   #define __NR_openat          56
   #define __NR_close           57

   /* Extended file operations */
   #define __NR_ftruncate       84   /* generic sync_file_range or ftruncate */
   #define __NR_truncate        84

   /* Time / waiting */
   #define __NR_select          1067
   #define __NR_poll            1068
   #define __NR_epoll_wait      1069
   #define __NR_vfork           1071
   #define __NR_wait4           1072  /* oldwait4 */

   /* Memory management */
   #define __NR_brk             214
   #define __NR_mmap            __NR3264_mmap  /* 222 */
   #define __NR_munmap          215
   #define __NR_mremap          216
   #define __NR_mprotect        226
   #define __NR_msync           227
   #define __NR_mlock           228
   #define __NR_munlock         229
   #define __NR_mlockall        230
   #define __NR_munlockall      231
   #define __NR_mincore         232
   #define __NR_madvise         233
   #define __NR_remap_file_pages 234
   #define __NR_swapon          224
   #define __NR_swapoff         225

   /* Process control */
   #define __NR_clone           220
   #define __NR_execve          221

   #define __NR_setxattr      5
   #define __NR_lsetxattr     6
   #define __NR_fsetxattr     7
   #define __NR_getxattr      8
   #define __NR_lgetxattr     9
   #define __NR_fgetxattr     10
   #define __NR_listxattr     11
   #define __NR_llistxattr    12
   #define __NR_flistxattr    13
   #define __NR_removexattr   14
   #define __NR_lremovexattr  15
   #define __NR_fremovexattr  16
   #define __NR_getcwd        17
   #define __NR_lookup_dcookie 18
   #define __NR_eventfd2      19
   #define __NR_epoll_create1 20
   #define __NR_epoll_ctl     21
   #define __NR_epoll_pwait   22
   #define __NR_dup           23
   #define __NR_dup3          24
   #define __NR3264_fcntl     25
   #define __NR_inotify_init1 26

   #define __NR_write      64
   #define __NR_mmap       222  // usually __NR3264_mmap
   #define __NR_munmap     215
   #define __NR_open       56   // usually __NR_openat
   #define __NR_close      57
   #define __NR_mprotect   226
#endif /* defined(__riscv) */

#endif // UNISTD_H
