name: Build and test
on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        c_compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM
        run: apt-get install clang llvm lld
      - name: Build, Install and Test
        shell: sh
        working-directory: ${{ github.workspace }}
        run: |
          export CC="${{ matrix.c_compiler }}"
          sh scripts/build.sh x86_64 linux
          sh scripts/install.sh /tmp
          sh scripts/test.sh x86_64
