name: Linux workflow
on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        c_compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM
        run: sudo apt-get install -y clang llvm lld
      - name: Build Interpreter
        shell: sh
        working-directory: ${{ github.workspace }}
        run: |
          export CC="${{ matrix.c_compiler }}"
          export CFLAGS="-O3 -c"
          export LD="${{ matrix.c_compiler }}"
          export LDFLAGS=""
          cd tuim
          make
      - name: Install Interpreter
        shell: sh
        working-directory: ${{ github.workspace }}
        run: |
          export TUIM_HOME=/opt/tuim
          sudo cp tuim/tuim/bin/tuim $TUIM_HOME/tuim
          sudo ln -sf $TUIM_HOME/tuim /usr/bin/tuim
