name: Build and test
on: [push, pull_request]

jobs:
  posix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        c_compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v4
      - name: Build, Install and Test
        shell: sh
        working-directory: ${{ github.workspace }}
        run: |
          . scripts/build.sh x86_64 linux
