name: Linux workflow
on: [push, pull_request]

jobs:
  amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM
        run: sudo apt-get install -y clang llvm lld
      - name: Build, install and test
        shell: sh
        working-directory: ${{ github.workspace }}
        run: |
          export TUIM_HOME="/opt/tuim"
          export PREFIX="/usr/local"
          cp tuim/src/arch-amd64.h ./arch.h
          cp tuim/etc/profile.d/environment-amd64.sh ./environment.sh
          sudo su -c "sh -e docs/assets/linux.sh"
  linux:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM
        run: sudo apt-get install -y clang llvm lld
      - name: Build, install and test
        shell: sh
        working-directory: ${{ github.workspace }}
        run: |
          export TUIM_HOME="/opt/tuim"
          export PREFIX="/usr/local"
          cp tuim/src/arch-aarch64.h ./arch.h
          cp tuim/etc/profile.d/environment-aarch64.sh ./environment.sh
          sudo su -c "sh -e docs/assets/linux.sh"
