name: Linux workflow
on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        c_compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM
        run: sudo apt-get install -y clang llvm lld
      - name: Build, Install and Test
        shell: sh
        working-directory: ${{ github.workspace }}
        run: |
          export CC="${{ matrix.c_compiler }}"
          sh scripts/build.sh x86_64 linux

          export TUIM_HOME=/opt/tuim
          sudo sh scripts/install.sh $TUIM_HOME
          sudo ln -sf $TUIM_HOME/tuim /usr/bin/tuim

          sh scripts/test.sh x86_64
