name: Linux workflow
on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        c_compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM
        run: sudo apt-get install -y clang llvm lld
      - name: Build Interpreter
        shell: sh
        env:
          CC: ${{ matrix.c_compiler }}
          CFLAGS: -O3 -c
          LD: ${{ matrix.c_compiler }}
          LDFLAG: ""
        working-directory: ${{ github.workspace }}
        run: |
          cd tuim
          make
      - name: Install Interpreter
        shell: sh
        working-directory: ${{ github.workspace }}
        run: |
          export TUIM_HOME=/opt/tuim
          sudo mkdir -p "${TUIM_HOME}"/{bin,include,lib,share}
          sudo cp tuim/bin/tuim $TUIM_HOME/tuim
