name: Linux workflow
on: [push, pull_request]

jobs:
  amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM
        run: sudo apt-get install -y clang llvm lld
      - name: Build, install and test
        shell: sh
        working-directory: ${{ github.workspace }}
        run: |
          export KERNEL="linux"
          export ARCH="amd64"
          export TUIM_HOME="/opt/tuim"
          sudo su -c "sh -e tuim/scripts/build.sh"
  aarch64:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM
        run: sudo apt-get install -y clang llvm lld
      - name: Build, install and test
        shell: sh
        working-directory: ${{ github.workspace }}
        run: |
          export KERNEL="linux"
          export ARCH="aarch64"
          export TUIM_HOME="/opt/tuim"
          sudo su -c "sh -e tuim/scripts/build.sh"
