name: Windows NT workflow
on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, amd64_x86, amd64_arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: ${{ matrix.arch }}
      - name: Build Interpreter
        env:
          CC: clang
          CFLAGS: -O3 -c -D __STDC__=1
          LD: clang
          LDFLAGS: ""
        working-directory: ${{ github.workspace }}
        run: |
          cd tuim
          make
