name: Windows NT workflow
on: [push, pull_request]

jobs:
  amd64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build, install and test
        working-directory: ${{ github.workspace }}
        run: |
          set KERNEL="windows_nt"
          set ARCH="amd64"
          set TUIM_HOME="C:\Program Files\Tuim"
          sh -e tuim/scripts/build.sh
  aarch64:
    runs-on: windows-11-arm
    steps:
      - uses: actions/checkout@v4
      - name: Build, install and test
        working-directory: ${{ github.workspace }}
        run: |
          set KERNEL="windows_nt"
          set ARCH="aarch64"
          set TUIM_HOME="C:\Program Files\Tuim"
          sh -e tuim/scripts/build.sh
