name: Windows NT workflow
on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, amd64_x86, amd64_arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: ${{ matrix.arch }}
      - name: Build Interpreter
        shell: sh
        working-directory: ${{ github.workspace }}
        run: |
          export CC="clang"
          export CFLAGS="-std=c23 -O3 -c"
          export LD="clang"
          export LDFLAGS=""
          cd tuim
          make
