# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  posix:
    runs-on: [ubuntu-latest, macos-latest]
    c_compiler: [gcc, clang]
    steps:
    - uses: actions/checkout@v4
    - name: Build Interpreter
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        cd interfaces
        mkdir bin
        export CC=${{ matrix.c_compiler }}
        exec ${CC} -o bin/tuim -D _POSIX_C_SOURCE=200809L src/main.c
  windows:
    runs-on: windows-latest
    c_compiler: cl
    steps:
    - uses: actions/checkout@v4
    - name: Build Interpreter
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        cd interfaces
        mkdir bin
        cl -o bin/tuim -D _POSIX_C_SOURCE=200809L src/main.c
        exit $?
#    - name: Archive output
#      uses: actions/upload-artifact@v4
#      with:
#        name: build-${{ matrix.os }}-${{ matrix.c_compiler }}
#        path: ${{ github.workspace }}/build.zip
