name: XNU workflow
on: [push, pull_request]

jobs:
  xnu:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        c_compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v4
      - name: Build Interpreter
        shell: sh
        working-directory: ${{ github.workspace }}
        run: |
          export CC="${{ matrix.c_compiler }}"
          export CFLAGS="-O3 -c"
          export LD="${{ matrix.c_compiler }}"
          export LDFLAGS=""
          cd tuim
          make
      - name: Install Interpreter
        shell: sh
        working-directory: ${{ github.workspace }}
        run: |
          export TUIM_HOME=/opt/tuim
          sudo mkdir -p "${TUIM_HOME}"/{bin,include,lib,share}
          sudo cp tuim/bin/tuim $TUIM_HOME/tuim
