name: XNU workflow
on: [push, pull_request]

jobs:
  aach64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build, install and test
        shell: sh
        env:
          OSTYPE: darwin
          ARCH: aarch64
          TUIM_HOME: /Applications/Tuim.app
        working-directory: ${{ github.workspace }}
        run: sudo su -c "sh -e tuim/scripts/build.sh"
  amd64:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Build, install and test
        shell: sh
        env:
          OSTYPE: darwin
          ARCH: amd64
          TUIM_HOME: /Applications/Tuim.app
        working-directory: ${{ github.workspace }}
        run: sudo su -c "sh -e tuim/scripts/build.sh"
