name: Build and test
on: [push, pull_request]

jobs:
  xnu:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        c_compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v4
      - name: Build, Install and Test
        shell: sh
        working-directory: ${{ github.workspace }}
        run: |
          export CC="${{ matrix.c_compiler }}"
          sh scripts/build.sh aarch64 xnu
          sh scripts/install.sh /tmp
          sh scripts/test.sh aarch64
