#if defined(__linux__)
   #include "linux/stdio.c"
#elif defined(_WIN32)
   #error "Not implemented yet."
#else
   #error "Unsupported OS."
#endif

//#include "remove.c"
//#include "rename.c"
//#include "tmpfile.c"
//#include "tmpnam.c"
//#include "fclose.c"
//#include "fflush.c"
//#include "fopen.c"
//#include "freopen.c"
//#include "setbuf.c"
//#include "setvbuf.c"
//#include "fprintf.c"
//#include "fscanf.c"
#include "printf.c"
//#include "scanf.c"
//#include "sprintf.c"
//#include "sscanf.c"
#include "vfprintf.c"
#include "vprintf.c"
//#include "vsprintf.c"
//#include "fgetc.c"
//#include "fgets.c"
#include "fputc.c"
#include "fputs.c"
//#include "getc.c"
//#include "getchar.c"
//#include "gets.c"
#include "putc.c"
#include "putchar.c"
#include "puts.c"
//#include "ungetc.c"
//#include "fread.c"
//#include "fwrite.c"
//#include "fgetpos.c"
//#include "fseek.c"
//#include "fsetpos.c"
//#include "ftell.c"
//#include "rewind.c"
//#include "clearerr.c"
//#include "feof.c"
//#include "ferror.c"
//#include "perror.c"
